export enum BlockTypeFlag {
    None = 0,

    // anonymous block generated by hatching, associative dimensioning,
    // other internal operations, or an application
    Anonymous = 1,

    // this bit is not set if the block has any attribute definitions that
    // are constant, or has no attribute definitions at all
    NonConstant = 2,

    // external referenced
    Xref = 4,
    XrefOverlay = 8,
    ExternallyDependent = 16,

    // resolved external reference, or dependent of an external reference
    ResolvedOrDependent = 32,

    // referenced external reference
    ReferencedXref = 64,
}
